qi_prog_track_prog_tracker_tasks:
    resource: "@QiProgTrackProgTrackerBundle/Controller/TasksController.php"
    type:     annotation

symfony_cebu_pages:
    resource: "@SymfonyCebuPagesBundle/Controller/"
    type:     annotation
    prefix:   /pages

app_user:
    resource: "@SymfonyCebuUserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

qi_prog_track_prog_tracker: 
    resource: "@QiProgTrackProgTrackerBundle/Controller/"
    type: annotation
    prefix: /home
